server:
  port: 8101

spring:
  application:
    name: ms-product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_product
    username: postgres
    password: admin

  jpa:
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml